name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # schedule:
  #   - cron: "0 3 * * *"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install chromium
      - name: Install Fonts
        run: sudo apt install fonts-ipafont-gothic
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 7
      - name: Slack Notification on Success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.18.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "username": "E2Eテスト"
              "icon_emoji": ":sunny:",
              "text": "E2Eテスト結果 *${{ job.status }}*",
              "attachments": [
                {
                  "color": "#2EB67D",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "E2Eテスト結果",
                        "emoji": true
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "Status：*${{ job.status }}*"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "RunId：*${{ github.run_id}}*"
                      }
                    }
                  ]
                }
              ]
            }
      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.18.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "username": "E2Eテスト"
              "icon_emoji": ":umbrella:",
              "text": "E2Eテスト結果 *${{ job.status }}*",
              "attachments": [
                {
                  "color": "#d90000",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "E2Eテスト結果",
                        "emoji": true
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "Status：*${{ job.status }}*"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "RunId：*${{ github.run_id}}*"
                      }
                    }
                  ]
                }
              ]
            }
